# Generated by Django 2.1.4 on 2018-12-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20181228_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
